/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import checkers.CheckersGameCreator
import chess.ChessGameCreator
import commons.GameEngineImpl
import edu.austral.dissis.chess.gui.CachedImageResolver
import edu.austral.dissis.chess.gui.DefaultImageResolver
import edu.austral.dissis.chess.gui.GameView
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    private val chess = GameEngineImpl(ChessGameCreator().createGame())
    private val checkers = GameEngineImpl(CheckersGameCreator().createGame())

    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle

        val root = GameView(checkers, imageResolver)
        primaryStage.scene = Scene(root)

        primaryStage.show()
    }
}